from typing import Any

from .base import BaseMixin

class LicenseMixin(BaseMixin):
    def create_new_license(
        self, shortName: str, fullName: str, text: str, checked: bool = False, license_details: dict[str, Any] = {}
    ) -> Any: ...
    def delete_license(self, license_shortname: str) -> bool: ...
    def download_license_info(
        self, project_id: str, filename: str, generator: str = "XhtmlGenerator", variant: str = "DISCLOSURE"
    ) -> None: ...
    def get_all_licenses(self) -> list[dict[str, Any]]: ...
    def get_license(self, license_id: str) -> dict[str, Any] | None: ...
