from typing import Any

from .base import BaseMixin

class ReleasesMixin(BaseMixin):
    def get_release(self, release_id: str) -> dict[str, Any] | None: ...
    def get_release_by_url(self, release_url: str) -> dict[str, Any] | None: ...
    def get_releases_by_name(self, name: str) -> list[Any]: ...
    def get_all_releases(
        self, fields: str = "", all_details: bool = False, page: int = -1, page_size: int = -1, sort: str = ""
    ) -> Any: ...
    def get_releases_by_external_id(self, ext_id_name: str, ext_id_value: str = "") -> list[dict[str, Any]]: ...
    def create_new_release(
        self, name: str, version: str, component_id: str, release_details: dict[str, Any] = {}
    ) -> dict[str, Any] | None: ...
    def update_release(self, release: dict[str, Any], release_id: str) -> dict[str, Any] | None: ...
    def update_release_external_id(
        self, ext_id_name: str, ext_id_value: str, release_id: str, update_mode: str = "none"
    ) -> dict[str, Any] | None: ...
    def delete_release(self, release_id: str) -> dict[str, Any] | None: ...
    def get_users_of_release(self, release_id: str) -> dict[str, Any] | None: ...
