class SW360OAuth2:
    def __init__(self, url: str, user: str, password: str) -> None: ...
    def create_client(self, description: str, writeable: bool = False) -> None: ...
    def generate_token(self) -> str: ...
    @property
    def token(self) -> str | None: ...
    @property
    def refresh_token(self) -> str: ...
    @property
    def url(self) -> str: ...
