from typing import Any

from .base import BaseMixin

class VendorMixin(BaseMixin):
    def get_all_vendors(self) -> list[dict[str, Any]]: ...
    def get_vendor(self, vendor_id: str) -> dict[str, Any] | None: ...
    def create_new_vendor(self, vendor: dict[str, Any]) -> dict[str, Any]: ...
    def update_vendor(self, vendor: dict[str, Any], vendor_id: str) -> dict[str, Any]: ...
    def delete_vendor(self, vendor_id: str) -> dict[str, Any]: ...
